src/openlayer/lib/core/base_model.py
src/openlayer/lib/integrations/langchain_callback.py
src/openlayer/lib/integrations/openai_tracer.py
src/openlayer/lib/tracing/steps.py
src/openlayer/lib/tracing/tracer.py
src/openlayer/lib/utils.py

Adds a `tracer.trace_async()` decorator that needs to be used on async functions. 
Also adds a `tracer.run_async_function` that needs to be used instead of `asyncio.run` when calling an awaitable function.

Async function tracing in dev mode

---

examples/tracing/anthropic/anthropic_tracing.ipynb
src/openlayer/lib/__init__.py
src/openlayer/lib/integrations/anthropic_tracer.py
src/openlayer/lib/tracing/tracer.py

- Introduces the `trace_anthropic` function. 
- `trace_anthropic` behaves the same way as `trace_openai` but with the `Anthropic` client.
- It works when `stream=True` or `False`, and parses text blocks and tool calls.
- Also introduces a notebook example showing how to trace Anthropic LLM calls and stream them to Openlayer.

feat: Add Anthropic tracer

---

src/openlayer/lib/integrations/langchain_callback.py

- Adds support for Vertex AI models via the LangChain callback handler. 
- Fixes the issue where the callback handler was not being triggered on LLM starts (just on chat model starts).
- I didn't add a notebook example for Vertex AI. I'll add a "native" Vertex AI example in the future, once we support tracing it directly (instead of via LangChain). The LangChain notebook example should be clear enough for now.

feat: support Vertex AI models via LangChain callback handler

---

examples/tracing/langchain/langchain_callback.ipynb

- Installs `langchain` and `langchain_openai` in the first cell.
- These dependencies are required by the notebook and their absence caused issues when running on Colab.

fix: add missing dependencies for LangChain notebook example

---

examples/tracing/anthropic/anthropic_tracing.ipynb

- Adds `anthropic` to the `pip install` cell.
- This dependency is required by the notebook and its absence caused issues when running on Colab.

fix: add missing dependency for Anthropic notebook example

---

examples/tracing/mistral/mistral_tracing.ipynb
src/openlayer/lib/__init__.py
src/openlayer/lib/integrations/mistral_tracer.py

- Adds the `trace_mistral` function, to trace interactions with Mistral AI LLMs.
- The method works for Mistral's `chat.complete` and `chat.stream` endpoints.
- Adds a Jupyter Notebook example illustrating the usage.

feat: add tracer for Mistral AI

---

examples/rest-api/stream_data.py

- Make the data stream example about tabular classification (so that it is consistent with the docs).
- Added extra comments to explain the process better.

improvement: make data stream example about tabular classification

---

src/openlayer/lib/data/commit.py

- Adds the `push` function to `/src/lib/data/commit.py` that enables pushing a commit from the Python SDK.
- It is supposed to be used as follows:
```python
from openlayer import Openlayer
from openlayer.lib.data import commit
client = Openlayer()
commit.push(
client=client,
directory="./my-project",  # Path to the project dir, with the `openlayer.json` and datasets
project_id=YOUR_PROJECT_ID_HERE,
message="Initial commit" # Defaults to 'New commit' 
)
```

feat(data): add function to push a commit to the platform

---

pyproject.toml

- Upgrade `pyarrow` version required due to Dependabot issue (https://github.com/openlayer-ai/openlayer-python/security/dependabot/13)

fix: update to pyarrow==14.0.1 to avoid dependabot issues

---

examples/tracing/rag/rag_tracing.ipynb

- Updates the URL for the context file (`context.txt`) used by the RAG tracing notebook.
- Previous URL pointed to the `examples-gallery` repo, which is deprecated. 
- Current URL points to the `templates` repo.

chore: update download URL for context file

---

src/openlayer/lib/tracing/tracer.py

- A column named `groundTruth` was always getting pulled from the root step, even when it was to `None`.
- Now, the ground truth value is only pulled from the root step if it is not `None`. In that case, it is also added to the config as the `groundTruthColumnName`.

fix(tracer): pull ground truth from root step only when it is defined

---

examples/tracing/pydantic-ai/pydantic_ai_tracing.ipynb

- Adds a notebook example for Pydantic AI (which leverages the OTel endpoint).

docs: add Pydantic AI notebook example

---

examples/tracing/openai/openai_agents_tracing.ipynb
src/openlayer/lib/integrations/__init__.py
src/openlayer/lib/integrations/openai_agents.py

This PR implements a complete **OpenAI Agents SDK integration** for the Openlayer Python SDK and provides a comprehensive Jupyter notebook example demonstrating its usage. This enables automatic tracing and monitoring of multi-agent workflows built with the OpenAI Agents SDK.
**Complete OpenAI Agents SDK Integration:**
- ✅ **`OpenlayerTracerProcessor`** - Main tracing processor class
- ✅ **Automatic span capture** - Traces all agent interactions, handoffs, and tool calls
- ✅ **Conversation flow tracking** - Maintains context across agent transitions
- ✅ **Performance monitoring** - Captures latency, token usage, and metrics
- ✅ **Error handling** - Comprehensive error capture and reporting
**Key Features:**
- **Agent workflow tracing** - Complete visibility into multi-agent conversations …

feat(integrations): Implement OpenAI Agents SDK Integration

---

src/openlayer/lib/integrations/langchain_callback.py
src/openlayer/lib/tracing/tracer.py

The Openlayer Python SDK was experiencing duplicate trace calls when using the `@trace()` decorator on async functions. Instead of generating a single unified trace, async functions created multiple duplicate traces with different data, causing test failures and incorrect tracing behavior.
The issue was traced to the `@trace_async()` decorator's incompatibility with async generator functions:
- The decorator used context managers (`with create_step()`) that interfered with `yield` statements
- This caused wrapper functions to return `coroutine` objects instead of `async_generator` objects
- The context manager became "stuck" waiting for generators to complete before finalizing steps
- Regular async functions worked correctly, but async generators failed
- **Detection**: Added …

fix: Fix Duplicate Trace Calls for Async Functions and Optimize Tracer Implementation

---

examples/tracing/bedrock/bedrock_tracing.ipynb
src/openlayer/lib/__init__.py
src/openlayer/lib/integrations/bedrock_tracer.py

Introduces the AWS Bedrock tracer.
Customer request.
The current implementation focuses on [Anthropic models](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages-request-response.html). Changes will be required to parse request/response from other LLM providers.

feat(integrations): add AWS Bedrock tracer

---

src/openlayer/lib/tracing/tracer.py

- Allow output overwrite in tracing.

feat: allow output overwrite

---

src/openlayer/lib/tracing/tracer.py

Fixed generator tracing to export concatenated chunks instead of generator objects to Openlayer. Previously, when using `@trace` or `@trace_async` decorators on functions that return generators (like OpenAI streaming), Openlayer would receive useless `<generator object>` instead of the actual concatenated content. This PR implements proper generator tracing that preserves streaming behavior while capturing meaningful trace data.
- Implemented `TracedSyncGenerator` class-based wrapper that delays trace creation until first iteration
- Added `inspect.isgeneratorfunction()` detection to handle generator functions separately from regular functions
- Created `_finalize_sync_generator_step()` helper function for proper cleanup and trace completion
- Leveraged existing `TracedAsyncGenerator` …

feat(tracing): enhance tracing for synchronous generator functions

---

src/openlayer/lib/integrations/__init__.py
src/openlayer/lib/integrations/langchain_callback.py

Implements the [AsyncCallbackHandler interface](https://python.langchain.com/api_reference/core/callbacks/langchain_core.callbacks.base.AsyncCallbackHandler.html) from LangChain, thus enabling tracing async workflows from LangChain/LangGraph.
POC request.

feat(integrations): async Openlayer callback handler

---

src/openlayer/lib/tracing/tracer.py

The `@trace` decorator for synchronous generators crashes in multi-threaded web frameworks like FastAPI and OpenWebUI with the following error:
```
ValueError: <Token var=<ContextVar name='current_step' at 0xffff98e7e520> at 0xffff982d7280> was created in a different Context
```
This error occurs when:
1. A traced generator function is called in one execution context (main thread)
2. The generator is consumed in a different execution context (worker thread via `starlette.concurrency.iterate_in_threadpool`)
3. The `_current_step.reset(token)` call in `_finalize_sync_generator_step()` attempts to reset a context variable token that was created in the original context
```python
@app.post("/stream")
async def stream_endpoint():
@trace()
def my_generator():
yield "chunk1"
yield "chunk2"
gen = …
```

fix(tracing): improve error handling in sync generator finalization

---

src/openlayer/lib/integrations/langchain_callback.py

`metadata_transformer` should be a transformation function (`Callable[[Dict[str, Any]], Dict[str, Any]]`) that is applied to the metadata object currently logged by the callback handler. This gives the user fine-grained control about the metadata logged.
The previous version of the callback handler didn't have the `on_new_token` method implemented. The current implementation handles the usage information, which is streamed at the very end when `stream_usage=True`.
Now, we're correctly logging the context on retrieval steps as well as on chains that contain `source_documents`. This enables context-dependent metrics on the platform
For example, if the user wants to exclude metadata fields that start with `langgraph`, a possible metadata transformer would be:
```python
def …
```

feat: accept metadata transformer for LangChain callback handler

---

src/openlayer/lib/integrations/langchain_callback.py
src/openlayer/lib/tracing/enums.py
src/openlayer/lib/tracing/steps.py
src/openlayer/lib/utils.py

Introduces the new step types. Namely `tool`, `agent`, `handoff`, and `retriever`. The new steps types are now used in the LangChain callback handler.
POC request.

feat: introduce new step types

---

pyproject.toml

`numpy` is no longer needed in the SDK. However, we were still pinning it as `numpy<2.0`. This PR removes the version pin.

fix: remove numpy dependency
